apiVersion: v2
name: coredns
description: A Helm chart for CoreDNS
type: application
version: 1.0.0
appVersion: v1.0.0
dependencies:
  - name: coredns
    version: 1.42.4
    repository: https://coredns.github.io/helm