---
coredns:
  replicaCount: 2
  service:
    clusterIP: 10.96.0.10
    clusterIPs:
      - 10.96.0.10
    ipFamilies:
      - IPv4
    ipFamilyPolicy: SingleStack

cilium-gateways:
  appName: "coredns"
  fqdn: "coredns.local"
  serviceName: "coredns"
  http:
    enabled: false
  tls:
    enabled: false
  tcp:
    enabled: true
    frontend:
      port: 53
    backend:
      port: 53
