---
appName: "my-app"
fqdn: ""                    # Fully Qualified Domain Name for the application
serviceName: "my-service"  # Name of the service to route traffic to  
http:
  enabled: true
  frontend:
    port: 80
  backend:
    port: 80
tls:
  enabled: false
  frontend:
    port: 443
  backend:
    port: 443
