---apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  gatewayClassName: cilium
  listeners:
  - name: http-listener
    protocol: HTTP
    port: 80
    #hostname: argocd.example.com               # use your Argo CD domain
    allowedRoutes:
      namespaces:
        from: Same
  - name: tls-listener
    protocol: TLS
    port: 443
    #hostname: argocd.example.com
    tls:
      mode: Passthrough                       # Allow end-to-end TLS (Gateway does not terminate)
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: argocd
spec:
  hostnames:
  - argocd.example.com                     # must match Gateway.listener.hostname
  parentRefs:
  - name: argocd-gateway                   # same name/namespace as the Gateway above
    sectionName: http-listener             # (selects the HTTP listener by name)
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argocd-server                  # ArgoCD Server service in the argocd namespace
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: argocd-tls-route
  namespace: argocd
spec:
  hostnames:
  - argocd.example.com
  parentRefs:
  - name: argocd-gateway
    sectionName: tls-listener              # refers to the TLS listener on the Gateway
  rules:
  - backendRefs:
    - name: argocd-server
      port: 443
