apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack
type: application
version: 1.0.0
appVersion: v1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 75.2.1
    repository: https://prometheus-community.github.io/helm-charts