apiVersion: v2
name: argocd
description: A Helm chart for ArgoCD
type: application
version: 1.0.0
appVersion: v1.0.0
dependencies:
  - name: argo-cd
    version: 8.1.0
    repository: https://argoproj.github.io/argo-helm
  - name: cilium-gateways
    version: 1.0.0
    repository: file://../cilium-gateways
