apiVersion: v2
name: cilium
description: A Helm chart for cilium
type: application
version: 1.0.0
appVersion: v1.0.0
dependencies:
  - name: cilium
    version: 1.18.0-pre.3
    repository: https://helm.cilium.io/