---
chartPath: argocd/charts
repoUrl: https://github.com/devopsjourney1/talos-homelab.git
destination:
  server: https://kubernetes.default.svc

apps:
  argocd:
    project: default
  cilium: {}
  coredns:
    namespace: kube-system
  argo-rollouts: {}
  kube-prometheus-stack:
    namespace: monitoring
  velero: {}
  portainer: {}
