---
chartPath: argocd/charts
repoUrl: https://github.com/devopsjourney1/talos-homelab.git
destination:
  server: https://kubernetes.default.svc

apps:
  argocd:
    project: default
  cilium:
    namespace: kube-system
  coredns:
    namespace: kube-system
  argo-rollouts:
    ignoreDifferences:
     - group: apiextensions.k8s.io
       kind: CustomResourceDefinition
       jsonPointers:
         - /spec/preserveUnknownFields
  kube-prometheus-stack:
    namespace: monitoring
  velero: {}
  portainer: {}
