---
cert-manager:
  crds:
    enabled: true
  config:
    enableGatewayAPI: true

cilium-gateways:
  appName: cert-manager
  fqdn: "cert-manager.local"
  serviceName: "cert-manager"
  http:
    enabled: true
    frontend:
      port: 80
    backend:
      port: 80
