---
portainer:
  enterpriseEdition:
    enabled: true
    image:
      tag: lts
  tls:
    force: true

cilium-gateways:
  appName: portainer
  fqdn: "portainer.local"
  serviceName: "portainer"
  tls:
    enabled: true
    frontend:
      port: 443
    backend:
      port: 9443
