---
portainer:
  enterpriseEdition:
    enabled: true
    image:
      repository: portainerci/portainer-ee
      tag: develop
  tls:
    force: true

cilium-gateways-ui:
  appName: portainer
  fqdn: "portainer.local"
  serviceName: "portainer"
  tls:
    enabled: true
    frontend:
      port: 443
    backend:
      port: 9443
cilium-gateways-tunnel:
  appName: portainer-tunnel
  fqdn: "portainer.local"
  serviceName: "portainer"
  tcp:
    enabled: true
    frontend:
      port: 8000
    backend:
      port: 30776
