---
portainer:
  enterpriseEdition:
    enabled: true
    image:
      tag: lts
  tls:
    force: true

cilium-gateways-ui:
  appName: portainer
  fqdn: "portainer.local"
  serviceName: "portainer"
  tls:
    enabled: true
    frontend:
      port: 443
    backend:
      port: 9443
cilium-gateways-tunnel:
  appName: portainer-tunenl
  fqdn: "portainer.local"
  serviceName: "portainer"
  http:
    enabled: true
    frontend:
      port: 8000
    backend:
      port: 30776
