{{- range $appName, $appConfig := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $appConfig.namespace | default $appName }}
    server: {{ $.Values.destination.server | default "https://kubernetes.default.svc" }}
  project: {{ $appConfig.project | default "default" }}
  source:
    repoURL: {{ $.Values.repoUrl}}
    targetRevision: {{ $appConfig.targetRevision | default "HEAD" }}
    path: {{ $.Values.chartPath }}/{{ $appName }}
    helm:
      valueFiles:
        - values.yaml
      ignoreMissingValueFiles: true
      valuesObject: {}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  {{- if $appConfig.ignoreDifferences }}
  {{- range $ignoreDiff := $appConfig.ignoreDifferences }}
  ignoreDifferences:
    - group: {{ $ignoreDiff.group }}
      kind: {{ $ignoreDiff.kind }}
      name: {{ $ignoreDiff.name }}
      jsonPointers:
      {{- range $pointer := $ignoreDiff.jsonPointers }}
      - {{ $pointer }}
      {{- end }}
    {{- end }}
    {{- end }}

---
{{- end }}
