apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.destination.server | default "https://kubernetes.default.svc" }}
  project: default
  source:
    repoURL: {{ .Values.repoUrl}}
    targetRevision: HEAD
    path: {{ .Values.chartPath }}/argocd
    helm:
      valueFiles:
        - values.yaml
      ignoreMissingValueFiles: true
  syncPolicy:
    automated: {}