---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
  namespace: kube-system
spec:
  blocks:
  - cidr: 192.168.1.128/28
  disabled: false
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: ingress-gateway
  externalIPs: true
  loadBalancerIPs: true
